In [ ]:
#https://github.com/krishnaik06/Word-Embedding/blob/master/Untitled2.ipynb

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:

### Vocabulary size-dictionary size
voc_size=10000

In [6]:
#step1- # one hot representation of all the words

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)
# 1670- the, 8136-glass, 5324-0f, 453-milk gives the index representation of all the words in a sentence

[[1670, 8136, 5324, 453], [1670, 8136, 5324, 8830], [1670, 7247, 5324, 6953], [566, 8902, 5881, 8531, 7574], [566, 8902, 5881, 8531, 7050], [9598, 1670, 93, 5324, 5589], [5919, 324, 9771, 8531]]


In [7]:
# step2- pass this one hot to an embedding layer for vector representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1670 8136 5324  453]
 [   0    0    0    0 1670 8136 5324 8830]
 [   0    0    0    0 1670 7247 5324 6953]
 [   0    0    0  566 8902 5881 8531 7574]
 [   0    0    0  566 8902 5881 8531 7050]
 [   0    0    0 9598 1670   93 5324 5589]
 [   0    0    0    0 5919  324 9771 8531]]


In [10]:
# providing the no. of features- each word will be represented by 10 vectors in an array
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:

print(model.predict(embedded_docs)) #converted to emdedding vectors

[[[-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772
    0.04137344 -0.04327708  0.03185734 -0.03726169  0.01232449]
  [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772
    0.04137344 -0.04327708  0.03185734 -0.03726169  0.01232449]
  [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772
    0.04137344 -0.04327708  0.03185734 -0.03726169  0.01232449]
  [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772
    0.04137344 -0.04327708  0.03185734 -0.03726169  0.01232449]
  [ 0.01827464  0.0189162  -0.00261365  0.021419    0.00952984
   -0.03731833  0.04242798  0.01003169 -0.01182641  0.02407101]
  [-0.03807022 -0.04072744 -0.01499624 -0.00144554 -0.0475494
   -0.03700728 -0.01050045 -0.02637051 -0.00704298 -0.03284566]
  [ 0.01115415  0.0037631   0.04661571 -0.01010522 -0.04920424
    0.046919   -0.00659911 -0.03955958 -0.00865381 -0.00630531]
  [-0.01040329 -0.01204249  0.03451658 -0.0215436   0.005132
    0.01238685  0.01274952 -0.02831888 -0.03138887 

In [14]:

embedded_docs[0] # for first sentencence the glass of milk

array([   0,    0,    0,    0, 1670, 8136, 5324,  453])

In [15]:

print(model.predict(embedded_docs)[0]) 
# 0 is converted to 10 vectors ad dimension is 10
# 0 is converted to 10 vectors ad dimension is 10
# 0 is converted to 10 vectors ad dimension is 10
#  0 is converted to 10 vectors ad dimension is 10
# the is converted to 10 vectors ad dimension is 10
# glass is converted to 10 vectors ad dimension is 10
# of is converted to 10 vectors ad dimension is 10
# milk is converted to 10 vectors ad dimension is 10
# therefore 10 arrays with 10 vectors for each word as dimension=10

[[-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772  0.04137344
  -0.04327708  0.03185734 -0.03726169  0.01232449]
 [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772  0.04137344
  -0.04327708  0.03185734 -0.03726169  0.01232449]
 [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772  0.04137344
  -0.04327708  0.03185734 -0.03726169  0.01232449]
 [-0.02306004  0.04710138 -0.00278397 -0.02031729 -0.02143772  0.04137344
  -0.04327708  0.03185734 -0.03726169  0.01232449]
 [ 0.01827464  0.0189162  -0.00261365  0.021419    0.00952984 -0.03731833
   0.04242798  0.01003169 -0.01182641  0.02407101]
 [-0.03807022 -0.04072744 -0.01499624 -0.00144554 -0.0475494  -0.03700728
  -0.01050045 -0.02637051 -0.00704298 -0.03284566]
 [ 0.01115415  0.0037631   0.04661571 -0.01010522 -0.04920424  0.046919
  -0.00659911 -0.03955958 -0.00865381 -0.00630531]
 [-0.01040329 -0.01204249  0.03451658 -0.0215436   0.005132    0.01238685
   0.01274952 -0.02831888 -0.03138887 -0.04494249]]
